import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
const axios = require('axios');
const niceList = require('../../../utils/niceList.json');
const MerkleTree = require('../../../utils/MerkleTree');


export default function Home() {
  const serverUrl = 'http://localhost:1225';

  const [name, setName] = useState('');
  const [response, setResponse] = useState('');

  const submitRequest = async () => {
    // TODO: how do we prove to the server we're on the nice list? 
    const tree = new MerkleTree(niceList);
    const index = niceList.findIndex(n => n === name);
    const proof = tree.getProof(index);

    const { data: gift } = await axios.post(`${serverUrl}/gift`, {
      // TODO: add request body parameters here!
      proof: proof,
      name: name
    });

    setResponse(gift);
  }

  return (
    <div className={styles.container}>
        <Head>
          <title>Merkle Tree Application</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Merkle Tree Application!
          </h1>

          <div className={styles.grid}>
            <p className={styles.card}>
              Name: <input label='Name' type='text' onChange={(e) => {setName(e.target.value)}}/>
            </p>
          </div>
          <div className={styles.grid}>
            <p className={styles.card} onClick={() => {submitRequest()}}>
              Submit
            </p>
          </div>
          {response ? (
              <div className={styles.grid}>
                {response}
              </div>
            ) : (
              <></>
            )
          }
        </main>
      </div>
    
  )
}
